name: Core tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Restore
        run: dotnet restore src/ProjectOen.Core.Tests/ProjectOen.Core.Tests.csproj
      - name: Build
        run: dotnet build src/ProjectOen.Core.Tests/ProjectOen.Core.Tests.csproj --no-restore -warnaserror
      - name: Test
        run: dotnet test src/ProjectOen.Core.Tests/ProjectOen.Core.Tests.csproj --no-build --verbosity normal
