using UnityEngine;

namespace ProjectOen.Art.Runtime
{
    /// <summary>
    /// Art-only runtime adapter for switching one SpriteRenderer between the
    /// canonical states generated by the production-art catalog. Gameplay code
    /// can call SetState without knowing asset paths or sprite file names.
    /// </summary>
    public sealed class ProductionArtSpriteStateController : MonoBehaviour
    {
        [SerializeField] private ProductionArtSpriteStateSet stateSet;
        [SerializeField] private SpriteRenderer targetRenderer;
        [SerializeField] private string initialState;
        [SerializeField] private bool applyInitialStateOnAwake = true;

        public ProductionArtSpriteStateSet StateSet => stateSet;
        public string CurrentState { get; private set; }

        private void Awake()
        {
            if (targetRenderer == null)
                targetRenderer = GetComponent<SpriteRenderer>();

            if (applyInitialStateOnAwake)
            {
                string state = string.IsNullOrWhiteSpace(initialState) && stateSet != null
                    ? stateSet.DefaultState
                    : initialState;
                if (!string.IsNullOrWhiteSpace(state))
                    SetState(state);
            }
        }

        public bool SetState(string stateKey)
        {
            if (stateSet == null || targetRenderer == null)
                return false;

            Sprite sprite;
            if (!stateSet.TryGetSprite(stateKey, out sprite))
                return false;

            targetRenderer.sprite = sprite;
            CurrentState = stateKey;
            return true;
        }

        public bool HasState(string stateKey)
        {
            return stateSet != null && stateSet.ContainsState(stateKey);
        }

        public void Configure(ProductionArtSpriteStateSet set, SpriteRenderer renderer, string stateKey)
        {
            stateSet = set;
            targetRenderer = renderer;
            initialState = stateKey;
        }
    }
}
